### ISSUE TITLE
Hovery overy timey thingy

### ISSUE THREAD

**Issue by michael-grace** [UniversityRadioYork/WebStudio#184]
Thats how Marks described it

**Comment by mstratford** [comment]
Please elaborate lol.

**Comment by michael-grace** [comment]
![image](https://user-images.githubusercontent.com/56653532/103720065-67e14b80-4fc2-11eb-947c-25530eedcaa0.png)
i _**think**_ we were talking about the pop up thing on showplanner with the track time and title/album info

**Comment by markspolakovs** [comment]
Yes, that. (Maybe not the name though, bit of a waste of space.)

**Comment by mstratford** [comment]
Ah right, that's achievable :)

**Comment by michael-grace** [comment]
i think its useful to, at least have the album, because on the item card, you only get title and artist. personally, i've needed to find the album name whilst presenting
